### ISSUE TITLE
exactly which node version will make this work?

### ISSUE THREAD

**Issue by xxronis** [brandonhorst/node-tray#1]
Hi,

Cannot install with most of node versions from 10.21 to 10.31, which exact version will install dependencies, is it npm dont really know :(
Thanks

``` shell
user@book:~/Node$ mkdir trayapp;cd trayapp
user@book:~/Node/trayapp$ npm init
```

among other try outs:

``` shell
user@book:~/Node/trayapp$ npm install native-app tray --save
npm WARN package.json trayapp@1.0.0 No description
npm WARN package.json trayapp@1.0.0 No repository field.
npm WARN package.json trayapp@1.0.0 No README data
npm http GET https://registry.npmjs.org/native-app
npm http GET https://registry.npmjs.org/tray
npm http 304 https://registry.npmjs.org/native-app
npm http 304 https://registry.npmjs.org/tray
npm http GET https://registry.npmjs.org/NodObjC
npm http 304 https://registry.npmjs.org/NodObjC
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/ffi
npm http GET https://registry.npmjs.org/ref-struct/0.0.6
npm http GET https://registry.npmjs.org/ref
npm http 304 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/ref-struct/0.0.6
npm http 304 https://registry.npmjs.org/ffi
npm http 304 https://registry.npmjs.org/ref
npm http GET https://registry.npmjs.org/ms/0.7.0
npm http GET https://registry.npmjs.org/ms/0.6.2
npm http 304 https://registry.npmjs.org/ms/0.7.0
npm http GET https://registry.npmjs.org/bindings
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/ms/0.6.2
npm http 304 https://registry.npmjs.org/bindings
npm http 304 https://registry.npmjs.org/nan

> ref@0.3.5 install /Users/user/Node/trayapp/node_modules/tray/node_modules/NodObjC/node_modules/ref
> node-gyp rebuild

gyp http GET http://nodejs.org/dist/v0.10.26/node-v0.10.26.tar.gz
gyp http 200 http://nodejs.org/dist/v0.10.26/node-v0.10.26.tar.gz
  CXX(target) Release/obj.target/binding/src/binding.o
  SOLINK_MODULE(target) Release/binding.node
  SOLINK_MODULE(target) Release/binding.node: Finished

> ref@0.3.5 install /Users/user/Node/trayapp/node_modules/native-app/node_modules/NodObjC/node_modules/ref
> node-gyp rebuild

  CXX(target) Release/obj.target/binding/src/binding.o
  SOLINK_MODULE(target) Release/binding.node
  SOLINK_MODULE(target) Release/binding.node: Finished

> ffi@1.2.7 install /Users/user/Node/trayapp/node_modules/tray/node_modules/NodObjC/node_modules/ffi
> node-gyp rebuild

  CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/types.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/java_raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/closures.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi64.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/darwin.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/darwin64.o
  LIBTOOL-STATIC Release/libffi.a
libtool: unrecognized option `-static'
libtool: Try `libtool --help' for more information.
make: *** [Release/libffi.a] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/user/.nvm/v0.10.26/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Darwin 13.4.0
gyp ERR! command "node" "/Users/user/.nvm/v0.10.26/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/user/Node/trayapp/node_modules/tray/node_modules/NodObjC/node_modules/ffi
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok

> ffi@1.2.7 install /Users/user/Node/trayapp/node_modules/native-app/node_modules/NodObjC/node_modules/ffi
> node-gyp rebuild


  CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/types.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/java_raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/closures.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi64.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/darwin.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/darwin64.o
  LIBTOOL-STATIC Release/libffi.a
libtool: unrecognized option `-static'
libtool: Try `libtool --help' for more information.
make: *** [Release/libffi.a] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/user/.nvm/v0.10.26/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Darwin 13.4.0
gyp ERR! command "node" "/Users/user/.nvm/v0.10.26/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/user/Node/trayapp/node_modules/native-app/node_modules/NodObjC/node_modules/ffi
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok
npm ERR! ffi@1.2.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ffi@1.2.7 install script.
npm ERR! This is most likely a problem with the ffi package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls ffi
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 13.4.0
npm ERR! command "/Users/user/.nvm/v0.10.26/bin/node" "/Users/user/.nvm/v0.10.26/bin/npm" "install" "native-app" "tray" "--save"
npm ERR! cwd /Users/user/Node/trayapp
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/user/Node/trayapp/npm-debug.log
npm ERR! not ok code 0
```

or 

``` shell
user@book:~/Node/trayapp$ nvm use v0.10.21
Now using node v0.10.21
user@book:~/Node/trayapp$ npm install native-app tray --save
npm WARN package.json trayapp@1.0.0 No description
npm WARN package.json trayapp@1.0.0 No repository field.
npm WARN package.json trayapp@1.0.0 No README data
npm http GET https://registry.npmjs.org/native-app
npm http GET https://registry.npmjs.org/tray
npm http 200 https://registry.npmjs.org/native-app
npm http 200 https://registry.npmjs.org/tray
npm http GET https://registry.npmjs.org/NodObjC
npm http 200 https://registry.npmjs.org/NodObjC
npm http GET https://registry.npmjs.org/ffi
npm http GET https://registry.npmjs.org/ref-struct/0.0.6
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/ref
npm http 200 https://registry.npmjs.org/ref-struct/0.0.6
npm http GET https://registry.npmjs.org/ref-struct/-/ref-struct-0.0.6.tgz
npm http 200 https://registry.npmjs.org/debug
npm http 200 https://registry.npmjs.org/ffi
npm http 200 https://registry.npmjs.org/ref-struct/-/ref-struct-0.0.6.tgz
npm http 200 https://registry.npmjs.org/ref
npm http GET https://registry.npmjs.org/ms/0.7.0
npm http GET https://registry.npmjs.org/ms/0.6.2
npm http GET https://registry.npmjs.org/bindings
npm http GET https://registry.npmjs.org/nan
npm http 200 https://registry.npmjs.org/ms/0.6.2
npm http GET https://registry.npmjs.org/ms/-/ms-0.6.2.tgz
npm http 200 https://registry.npmjs.org/nan
npm http 200 https://registry.npmjs.org/ms/0.7.0
npm http GET https://registry.npmjs.org/ms/-/ms-0.7.0.tgz
npm http 200 https://registry.npmjs.org/bindings
npm http 200 https://registry.npmjs.org/ms/-/ms-0.6.2.tgz

> ref@0.3.5 install /Users/user/Node/trayapp/node_modules/tray/node_modules/NodObjC/node_modules/ref
> node-gyp rebuild

npm http 200 https://registry.npmjs.org/ms/-/ms-0.7.0.tgz

> ref@0.3.5 install /Users/user/Node/trayapp/node_modules/native-app/node_modules/NodObjC/node_modules/ref
> node-gyp rebuild

gyp http GET http://nodejs.org/dist/v0.10.21/node-v0.10.21.tar.gz
gyp http GET http://nodejs.org/dist/v0.10.21/node-v0.10.21.tar.gz

> ffi@1.2.7 install /Users/user/Node/trayapp/node_modules/tray/node_modules/NodObjC/node_modules/ffi
> node-gyp rebuild

gyp http GET http://nodejs.org/dist/v0.10.21/node-v0.10.21.tar.gz
gyp http 200 http://nodejs.org/dist/v0.10.21/node-v0.10.21.tar.gz
gyp http 200 http://nodejs.org/dist/v0.10.21/node-v0.10.21.tar.gz
gyp http 200 http://nodejs.org/dist/v0.10.21/node-v0.10.21.tar.gz

> ffi@1.2.7 install /Users/user/Node/trayapp/node_modules/native-app/node_modules/NodObjC/node_modules/ffi
> node-gyp rebuild

gyp http GET http://nodejs.org/dist/v0.10.21/node-v0.10.21.tar.gz
gyp http 200 http://nodejs.org/dist/v0.10.21/node-v0.10.21.tar.gz
  CXX(target) Release/obj.target/binding/src/binding.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
  CXX(target) Release/obj.target/binding/src/binding.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/types.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/types.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/java_raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/java_raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/closures.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/closures.o
  SOLINK_MODULE(target) Release/binding.node
  SOLINK_MODULE(target) Release/binding.node
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi64.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi64.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/darwin.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/darwin.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/darwin64.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/darwin64.o
  LIBTOOL-STATIC Release/libffi.a
  LIBTOOL-STATIC Release/libffi.a
libtool: unrecognized option `-static'
libtool: Try `libtool --help' for more information.
libtool: unrecognized option `-static'
libtool: Try `libtool --help' for more information.
make: make: *** [Release/libffi.a] Error 1*** [Release/libffi.a] Error 1

gyp ERR! gypbuild error
ERR! build error
gypgyp  ERR!ERR!  stackstack Error: `make` failed with exit code: 2
 Error: `make` failed with exit code: 2
gypgyp  ERR!ERR!  stackstack     at ChildProcess.onExit (/Users/user/.nvm/v0.10.21/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
     at ChildProcess.onExit (/Users/user/.nvm/v0.10.21/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp gyp ERR! ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
stackgyp      at ChildProcess.EventEmitter.emit (events.js:98:17)
ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! gyp ERR! System Darwin 13.4.0
gyp ERR! command "node" "/Users/user/.nvm/v0.10.21/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! System Darwin 13.4.0
gyp ERR! command "node" "/Users/user/.nvm/v0.10.21/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/user/Node/trayapp/node_modules/tray/node_modules/NodObjC/node_modules/ffi
gyp cwdERR! /Users/user/Node/trayapp/node_modules/native-app/node_modules/NodObjC/node_modules/ffi
gyp ERR! node -v v0.10.21
 node -vgyp v0.10.21
 ERR! gypnode-gyp -v  v0.10.10
ERR! gyp node-gyp -v v0.10.10
ERR! gypnot ok
ERR! not ok
npm ERR! weird error 1
ld: can't open output file for writing: Release/binding.node, errno=2 for architecture x86_64
ld: can't open output file for writing: Release/binding.node, errno=2 for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/binding.node] Error 1
make: *** [Release/binding.node] Error 1
gyp ERR! build error
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/user/.nvm/v0.10.21/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! gyp ERR! stack Error: `make` failed with exit code: 2
gypSystem  Darwin 13.4.0
ERR! stackgyp     at ChildProcess.onExit (/Users/user/.nvm/v0.10.21/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
 ERR!gyp  command "node" "/Users/user/.nvm/v0.10.21/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
ERR! stackgyp     at ChildProcess.EventEmitter.emit (events.js:98:17)
 gypERR!  ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! cwd /Users/user/Node/trayapp/node_modules/native-app/node_modules/NodObjC/node_modules/ref
gyp ERR! node -v v0.10.21
gyp ERR!System  Darwin 13.4.0
node-gyp -v v0.10.10
gypgyp  ERR! ERR! not okcommand "node" "/Users/user/.nvm/v0.10.21/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"

gyp ERR! cwd /Users/user/Node/trayapp/node_modules/tray/node_modules/NodObjC/node_modules/ref
gyp ERR! node -v v0.10.21
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok
npm ERR! not ok code 0
user@book:~/Node/trayapp$ nvm ls

  v0.10.21
  v0.10.22
  v0.10.26
  v0.10.31
  v0.11.11
current:    v0.10.21
```

...and others

**Comment by brandonhorst** [comment]
I'm running into some installation problems now too. I have a working copy locally (on 10.36) - probably some changes in ffi. I'll investigate this evening, may be able to fix by restricting the package.json version.

**Comment by brandonhorst** [comment]
This works on my system:

``` sh
tmp> nvm use 0.10
Now using node v0.10.36

tmp> git clone https://github.com/brandonhorst/node-tray.git
Cloning into 'node-tray'...
remote: Counting objects: 33, done.
remote: Total 33 (delta 0), reused 0 (delta 0), pack-reused 33
Unpacking objects: 100% (33/33), done.
Checking connectivity... done.

tmp> cd node-tray

node-tray> npm install
|
> ref@0.3.5 install /private/tmp/node-tray/node_modules/NodObjC/node_modules/ref
> node-gyp rebuild

  CXX(target) Release/obj.target/binding/src/binding.o
  SOLINK_MODULE(target) Release/binding.node
  SOLINK_MODULE(target) Release/binding.node: Finished

> ffi@1.2.7 install /private/tmp/node-tray/node_modules/NodObjC/node_modules/ffi
> node-gyp rebuild

  CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/types.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/java_raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/closures.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi64.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/darwin.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/darwin64.o
  LIBTOOL-STATIC Release/libffi.a
  CXX(target) Release/obj.target/ffi_bindings/src/ffi.o
  CXX(target) Release/obj.target/ffi_bindings/src/callback_info.o
  CXX(target) Release/obj.target/ffi_bindings/src/threaded_callback_invokation.o
  SOLINK_MODULE(target) Release/ffi_bindings.node
ld: warning: could not create compact unwind for _ffi_call_unix64: does not use RBP or RSP based frame
  SOLINK_MODULE(target) Release/ffi_bindings.node: Finished
native-app@1.0.2 node_modules/native-app

NodObjC@1.0.0 node_modules/NodObjC
├── ref-struct@0.0.6 (debug@1.0.4)
├── debug@2.1.3 (ms@0.7.0)
├── ref@0.3.5 (bindings@1.2.1, nan@1.5.3)
└── ffi@1.2.7 (bindings@1.2.1)
node-tray> npm run demo
...success
```

OS: Mac OS 10.10.2

XCode Command Line Tools:

``` sh
tmp> pkgutil --pkg-info=com.apple.pkg.CLTools_Executables
version: 6.2.0.0.1.1424975374
```

Let me know if this provides any insight.

Warning: Until I get confirmation that ffi/NodObjC are going to be working with 0.12/iojs eventually, I don't plan on making project production-ready.

**Comment by xxronis** [comment]
hmm still got problems with ffi@1.2.7 with nodev0.10.38 but on a OS10.9.5 machine
we got the same version of CLI tools though, anyway

Mac OS 10.9.5
package-id: com.apple.pkg.CLTools_Executables
version: 6.2.0.0.1.1424975374

I'll soon have feedback testing on an updated machine, cheers

**Comment by brandonhorst** [comment]
I have no way of testing on 10.9 right now. Could you try installing ffi@1.2.7 on its own, and see if the problem exists outside of a `node-tray` context?

Also, could you try out the just-released ffi@1.3.0? node-tray and node-native-app will be moving to that version as soon as possible.

**Comment by xxronis** [comment]
yeah getting the same with just _npm install ffi_ @1.2 or 1.3

``` shell
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/user/.nvm/v0.10.38/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 13.4.0
gyp ERR! command "node" "/Users/user/.nvm/v0.10.38/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/user/Node/fftest/node_modules/ffi
gyp ERR! node -v v0.10.38
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! ffi@1.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ffi@1.3.0 install script.
npm ERR! This is most likely a problem with the ffi package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls ffi
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 13.4.0
npm ERR! command "/Users/user/.nvm/v0.10.38/bin/node" "/Users/user/.nvm/v0.10.38/bin/npm" "install" "ffi"
npm ERR! cwd /Users/user/Node/fftest
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

Similar ffi-node-gyp errors on latest Yosemite and CLI tools 0.10.38 and latest npm
How to diagnose more?

**Comment by brandonhorst** [comment]
Unfortunately, I don't know - I have no expertise with ffi. I'd recommend opening up an issue [there](https://github.com/node-ffi/node-ffi).

As this is (unfortunately) unrelated to node-tray, I'll close this out.
